export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const ADD_IMAGE_SUCCESS = "ADD_IMAGE_SUCCESS";
export const EDIT_IMAGE_SUCCESS = "EDIT_IMAGE_SUCCESS";
export const DELETE_IMAGE_SUCCESS = "DELETE_IMAGE_SUCCESS";
export const GET_IMAGES_SUCCESS = "GET_IMAGES_SUCCESS";
export const GET_IMAGES_PAGINATED_SUCCESS = "GET_IMAGES_PAGINATED_SUCCESS";
export const CHANGE_SORT = "CHANGE_SORT";
export const ADD_VIEW_SUCCESS = "ADD_VIEW_SUCCESS";
export const GET_IMAGE_SUCCESS = "GET_IMAGE_SUCCESS";

export const LIKE_SUCCESS = "LIKE_SUCCESS";
export const DISLIKE_SUCCESS = "DISLIKE_SUCCESS";
export const DELETE_LIKE_SUCCESS = "DELETE_LIKE_SUCCESS";
export const FAVORITE_SUCCESS = "FAVORITE_SUCCESS";
export const DELETE_FAVORITE_SUCCESS = "DELETE_FAVORITE_SUCCESS";

export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const EDIT_COMMENT_SUCCESS = "EDIT_COMMENT_SUCCESS"
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";